.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Build ArcticDB against libevent 2.1.10 and 2.1.12

.ci_support/linux_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.9.____cpython.yaml, recipe/meta.yaml
=> Specify dependency on aws-crt-cpp >=0.19.8

recipe/meta.yaml
Checklist
Do not depend on `enum-compat` which only was needed for python < 3.4.
=> Do not depend on enum-compat

.ci_support/linux_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.9.____cpython.yaml, recipe/meta.yaml
=> arcticdb v1.3.1

recipe/meta.yaml
=> arcticdb 1.4.0

.github/CODEOWNERS, README.md, recipe/meta.yaml
Mainly add new maintainers from @man-group.
---
Checklist
=> maint: Miscellaneous changes

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.9.____cpython.yaml, .scripts/run_osx_build.sh, recipe/conda_build_config.yaml, recipe/meta.yaml
=> arcticdb v1.6.1rc0

recipe/meta.yaml
=> Update to 1.6.1rc1

recipe/meta.yaml
=> Update to 1.6.1rc2

recipe/meta.yaml
=> [rc] Rebuild without pin on `xxhash <0.8.2`

recipe/meta.yaml
=> Rebuild without pin on `xxhash <0.8.2`

recipe/meta.yaml
=> Pin Folly on 2023.08.07.00

recipe/meta.yaml
=> Pre-release: Upgrade to 2.0.0rc0

recipe/meta.yaml
Checklist
Towards https://github.com/man-group/ArcticDB/issues/765#issuecomment-1686042733.
For context see https://github.com/man-group/ArcticDB/issues/765#issuecomment-1691584314.
=> Rebuild against folly runtime-constrained builds

recipe/meta.yaml
=> [rc] arcticdb v3.0.0rc2

recipe/meta.yaml
=> arcticdb 4.0.0rc2

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.8.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
Checklist
To merge once https://github.com/conda-forge/arcticdb-feedstock/pull/63/files has been merged
=> Sync `libevent-2.1.10` with `main`

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.8.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
Checklist
Companion PR for https://github.com/conda-forge/arcticdb-feedstock/pull/67.
=> [`libevent-2.1.10`] arcticdb v4.0.0

recipe/meta.yaml
Checklist
This updates `main` to remove its minor discrepancies with `rc`.
=> [`main`] Sync with `rc`

recipe/meta.yaml
Checklist
This updates `libevent-2.1.10` to remove its minor discrepancies with `rc`.
=> [`libevent-2.1.10`] Sync with `rc`

.ci_support/linux_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.9.____cpython.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> arcticdb v1.6.2rc0

.ci_support/linux_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/migrations/aws_sdk_cpp111156.yaml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.9.____cpython.yaml, recipe/meta.yaml
=> [`rc`] Rebuild for aws_sdk_cpp111156

.ci_support/linux_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.9.____cpython.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> arcticdb v1.6.2

.ci_support/migrations/aws_sdk_cpp111156.yaml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.9.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
=> ArcticDB v4.1.0rc0

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
Checklist
See: https://github.com/man-group/ArcticDB/pull/1050/
=> pin: `libmongocxx < 3.9`

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/osx_64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_64_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.8.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12python3.9.____cpython.yaml, .github/CODEOWNERS, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
Checklist
See: https://github.com/man-group/ArcticDB/pull/1050/
=> [1.6.X] pin: `libmongocxx < 3.9`

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
=> [rc] pin: `libmongocxx < 3.9`

.ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.8.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.8.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.9.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.10.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.11.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10python3.9.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.10.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.11.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12python3.9.____cpython.yaml, recipe/meta.yaml
Checklist
Adding it to zip_keys does not work.
=> [rc] Pin `libprotobuf <4`

recipe/meta.yaml
=> [libevent-2.1.10] arcticdb v4.2.0

.ci_support/migrations/aws_sdk_cpp111210.yaml, recipe/meta.yaml
=> arcticdb v4.2.0

recipe/meta.yaml
=> [libevent-2.1.10] arcticdb v4.2.1

recipe/meta.yaml
=> arcticdb v4.2.1

recipe/meta.yaml
=> [libevent-2.1.10] Run python test suite

.ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.11.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.10.____cpython.yaml, .ci_support/osx_64_python3.11.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/osx_arm64_python3.10.____cpython.yaml, .ci_support/osx_arm64_python3.11.____cpython.yaml, .ci_support/osx_arm64_python3.9.____cpython.yaml, recipe/meta.yaml
=> Explicitly build against libcurl and openssl

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_nodejs18python3.9.____cpython.yaml, .ci_support/linux_64_nodejs20python3.9.____cpython.yaml, .gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, README.md, recipe/meta.yaml
=> [libevent-2.1.10] Explicitly build against libcurl and openssl

.ci_support/linux_64_libevent2.1.10python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12python3.9.____cpython.yaml, .gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, recipe/meta.yaml
=> [1.6.X] Explicitly build against libcurl and openssl

recipe/meta.yaml
=> [rc] Reintroduce attrs as a runtime dependency

.ci_support/linux_64_nodejs18python3.9.____cpython.yaml, .ci_support/linux_64_nodejs20python3.9.____cpython.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> [libevent-2.1.10] arcticdb v4.3.0

recipe/meta.yaml
=> 4.3.0 Second Build

recipe/meta.yaml
=> [libevent-2.1.10] 4.3.0 Second Build

recipe/meta.yaml
=> [libevent-2.1.10] arcticdb v4.3.1

.azure-pipelines/azure-pipelines-osx.yml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_azure_identity_cpp_azure_storage_blobs_cpp_libevent2.1.12numpy1.23python3.11.____cpython.yaml, .scripts/run_osx_build.sh, README.md, azure-pipelines.yml, recipe/meta.yaml
=> Changes for 4.4.0rc2

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_nodejs18numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_nodejs20numpy1.22python3.9.____cpython.yaml, .github/CODEOWNERS, README.md, recipe/meta.yaml
=> [libevent-2.1.10] arcticdb v4.4.0

recipe/meta.yaml
=> arcticdb v4.4.1

recipe/meta.yaml
=> [libevent-2.1.10] arcticdb v4.4.1

.azure-pipelines/azure-pipelines-osx.yml, recipe/meta.yaml
=> ArcticDB v4.4.2rc0

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.8.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/migrations/aws_sdk_cpp111329.yaml, .ci_support/migrations/krb5121.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.10.2azure_identity_cpp1.5.1azure_storage_blobs_cpp12.9.0libevent2.1.10numpy1.23python3.11.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
=> Release 4.4.3rc1

.scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
=> Release 4.4.3

.ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.8.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.8.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.23python3.11.____cpython.yaml, recipe/meta.yaml
=> Release 4.5.0rc1

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.8.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, README.md, recipe/build.sh, recipe/conda_build_config.yaml, recipe/meta.yaml
=> [rc] Add extra alternative builds on `aws-sdk-cpp==1.11.210`

.scripts/build_steps.sh, recipe/meta.yaml
=> [rc] arcticdb 4.5.0rc2

recipe/meta.yaml
=> Unpin libcxx <18

recipe/meta.yaml
=> Release 4.5.0rc4

.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_numpy1.22python3.8.____cpython.yaml, .ci_support/linux_64_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/migrations/aws_sdk_cpp111379.yaml, .ci_support/migrations/glog07.yaml, .ci_support/osx_64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml, recipe/meta.yaml
=> arcticdb 4.5.0

.azure-pipelines/azure-pipelines-osx.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, azure-pipelines.yml, recipe/meta.yaml
=> ArcticDB v4.5.1rc3

recipe/meta.yaml
=> ArcticDB v4.5.1rc4

.scripts/build_steps.sh, azure-pipelines.yml, recipe/meta.yaml
=> [libevent-2.1.10] ArcticDB v4.5.1

.scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
=> ArcticDB v5.0.0rc0

recipe/meta.yaml
=> ArcticDB v5.0.0rc1

.ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.23python3.11.____cpython.yaml, .scripts/run_osx_build.sh, azure-pipelines.yml, recipe/meta.yaml
=> 5.1.0rc0 release candidate

.github/CODEOWNERS, README.md, recipe/meta.yaml
=> Add IvoDD as maintainer on rc branch

.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml, .scripts/run_osx_build.sh, azure-pipelines.yml, recipe/meta.yaml
=> Release 5.1.0

.ci_support/linux_64_aws_sdk_cpp1.10.57nodejs18numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57nodejs20numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210nodejs18numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210nodejs20numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_nodejs18numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_nodejs20numpy1.22python3.9.____cpython.yaml, azure-pipelines.yml, recipe/meta.yaml
=> Release v5.1.0

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp1.11.1libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp1.11.1libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_azure_core_cpp_libevent_numpy1.23python3.11.____cpython.yaml, .scripts/run_osx_build.sh, build-locally.py, recipe/meta.yaml
=> ArcticDB v5.1.1rc0

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_aws_sdk_cpp1.10.57nodejs20numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.10.57nodejs22numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210nodejs20numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp1.11.210nodejs22numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_nodejs20numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_aws_sdk_cpp_nodejs22numpy1.22python3.9.____cpython.yaml, README.md, build-locally.py, recipe/meta.yaml
=> [libevent-2.1.10] Arcticdb v5.1.1

recipe/meta.yaml
=> ArcticDB 5.1.2rc0

.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/migrations/spdlog113.yaml, .ci_support/osx_64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml, .github/CODEOWNERS, README.md, recipe/meta.yaml
=> ArcticDB 5.1.2

.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpython.yaml, .ci_support/migrations/aws_sdk_cpp111458.yaml, .ci_support/migrations/libgrpc167_libprotobuf5282.yaml, .ci_support/migrations/lz4_c110.yaml, .ci_support/migrations/xz_to_liblzma_devel.yaml, .ci_support/osx_64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml, .github/CODEOWNERS, README.md, recipe/meta.yaml
Closes #331 
Closes #344
Closes #361
Closes #363
=> Pick up some open migrations

.ci_support/migrations/xz_to_liblzma_devel.yaml, recipe/meta.yaml
=> Rebuild for xz_to_liblzma_devel

recipe/meta.yaml
=> arcticdb v5.2.5

recipe/meta.yaml
Changes are based on:
Build number is based on: https://anaconda.org/conda-forge/arcticdb/files?version=5.2.1
Checklist
=> [5.2.x] ArcticDB v5.2.1

.scripts/run_docker_build.sh, build-locally.py, recipe/meta.yaml
Changes are based on: https://github.com/conda-forge/arcticdb-feedstock/commit/1dfbf27b9f749ca0809f3ed9f938fbc76f96fc5d
Build number is based on: https://anaconda.org/conda-forge/arcticdb/files?version=5.2.5
Checklist
=> [5.2.x] arcticdb 5.2.5

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .ci_support/linux_64_libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/linux_64_libevent2.1.12numpy1.22python3.10.____cpython.yaml, .ci_support/linux_64_libevent2.1.12numpy1.22python3.9.____cpython.yaml, .ci_support/linux_64_libevent2.1.12numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/osx_64_libevent2.1.12numpy1.22python3.10.____cpython.yaml, .ci_support/osx_64_libevent2.1.12numpy1.22python3.9.____cpython.yaml, .ci_support/osx_64_libevent2.1.12numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.10numpy1.23python3.11.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12numpy1.22python3.10.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12numpy1.22python3.9.____cpython.yaml, .ci_support/osx_arm64_libevent2.1.12numpy1.23python3.11.____cpython.yaml, README.md, recipe/conda_build_config.yaml, recipe/meta.yaml
Checklist
For context, see: https://github.com/conda-forge/arrow-cpp-feedstock/issues/1741#issuecomment-2784443963.
=> [`5.1.x`] Remove Azure SDK libraries from build variant

recipe/meta.yaml
=> arcticdb v5.3.1

recipe/meta.yaml
=> arcticdb v5.3.2
